### ISSUE TITLE
The AZURE_PW_TEST_RUN_ID is not available as a variable for other tasks

### ISSUE THREAD

**Issue by estruyf** [alexneo2003/playwright-azure-reporter#72]
Hi, I was testing the reporter and found out that the `AZURE_PW_TEST_RUN_ID` is not available as an environment variable for other tasks to use.

```bash
echo $(AZURE_PW_TEST_RUN_ID)

# Results in
AZURE_PW_TEST_RUN_ID: command not found
```

In issue #69 there was the suggestion to create a custom reporter to send out an email, but if you want to use the `AZURE_PW_TEST_RUN_ID` in the next steps of your pipeline.

I suggest creating it as an environment variable in the pipeline so that other tasks can use it.

It can be achieved by using the https://www.npmjs.com/package/azure-pipelines-task-lib dependency

```ts
setVariable("AZURE_PW_TEST_RUN_ID", runId, false, false);

// Or as an output variable
setVariable("AZURE_PW_TEST_RUN_ID", runId, false, true);
```

Now you could run: 

```bash
echo $(AZURE_PW_TEST_RUN_ID)

# Results in
1234
```

**Comment by alexneo2003** [comment]
@estruyf 
can you check beta package?
```bash
@alex_neo/playwright-azure-reporter@1.10.0-beta.0
```

**Comment by estruyf** [comment]
@alexneo2003 I've tested out the beta, and it works. Make sure to add documentation that you've created an output variable that requires the task name and variable name.

```yaml
- script: npx playwright test
  displayName: "Run Playwright tests"
  name: "playwright"
  env:
    CI: "true"

- script: echo $(playwright.AZURE_PW_TEST_RUN_ID)
  displayName: "Print test run id"
```

The output variable's benefit compared to an environment variable is that it can be used in future jobs.
