### ISSUE TITLE
[Feature] Expand testCaseIDMatcher to work with annotations

### ISSUE THREAD

**Issue by Az8th** [alexneo2003/playwright-azure-reporter#78]
Hello,

I just seen that #76 was resolved, thanks for the improvement !
As I realised that it was very close to the initial purpose of #55, except it would focus on annotations rather than tags, would it be possible to add the support for it please ?

It would be much less visible on the main page of the test report, but would still be visible when reviewing a specific test, with the possibility to directly add a clickable link to the test plan.

### Example:
_Using the new matcher_
```typescript
testCaseIdMatcher: azureTestID,
```
_If needed, a parameter to specify where to search ID between tag, titles or annotations could be added_
```typescript
testCaseIdZone: ['title', 'annotation'],
```
_Specifying test ID using annotation_
```typescript
test("Title", {
  tag: ['@tag1', '@tag2'],
  annotation: [{ type: 'azureTestID', description: '42' }]
  }, async ({ page }) => {
  //perform actions
});
```

**Comment by alexneo2003** [comment]
@Az8th 
I have published beta version, can you check it?
```bash
@alex_neo/playwright-azure-reporter@1.12.0-beta.0
```
also you can read [README ](https://www.npmjs.com/package/@alex_neo/playwright-azure-reporter/v/1.12.0-beta.0) about version

**Comment by Az8th** [comment]
Waow ! Nice work, will test it today ;)

**Comment by Az8th** [comment]
@alexneo2003 Works like a charm, thanks for your work !

Just wondering if `testCaseIdZone` should have separate `title` and `tags` values.
I initially thought that due to the old way of declaring them (in the title with an @), they were not separated, but it seems that the API now include a separate [testInfo.tags](https://playwright.dev/docs/api/class-testinfo#test-info-tags) property !

There is only one thing that I can't recover from my prior setup though, in order to have the `Tests` tab in the pipeline run, I use the following task in my pipeline file:
```yaml
 - task: PublishTestResults@2
    displayName: "Tests reports publication on Azure"
    condition: eq(variables['initDone'], 'true')
    inputs:
      searchFolder: "Reports"
      testResultsFiles: "e2e-junit-results.xml"
      testResultsFormat: "JUnit"
      mergeTestResults: true
      failTaskOnFailedTests: false
      testRunTitle: "${{parameters.project}} Playwright tests"
```
And use this reporter in the Playwright config file : `['junit', { outputFile: 'Reports/e2e-junit-results.xml' }]`

Nevetheless, as this task also creates a test run, I removed it to avoid duplicates, but the tab is no longer visible on my pipeline run. What is strange is that both `Test results` tab acts the same when comparing Test run reports. Am I missing something to make this appear, or is it not supported yet, and shall open a dedicated issue ?
